import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// Type definitions for the PDF generator
export interface PDFTableColumn {
    header: string;
    dataKey: string;
}

export interface PDFGenerationOptions {
    title: string;
    subTitle?: string;
    reportType: string;
    generatedBy: string;
    orientation?: 'portrait' | 'landscape';
    tableData: any[];
    tableColumns: PDFTableColumn[];
    fileName: string;
    // Metadata key-value pairs to display below header (e.g., "Batch ID": "123")
    metaData?: Record<string, string>;
}

export const generatePDF = (options: PDFGenerationOptions) => {
    const {
        title,
        reportType,
        generatedBy,
        orientation = 'portrait',
        tableData,
        tableColumns,
        fileName,
        metaData
    } = options;

    const doc = new jsPDF({
        orientation: orientation,
        unit: 'mm',
        format: 'a4'
    });

    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;

    // ==============================
    // HEADER SECTION
    // ==============================
    const leftMargin = 15;
    const rightMargin = pageWidth - 15;
    let currentY = 15;

    // Company Name
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("GOLDEN TEXTILE DYERS", leftMargin, currentY);

    // Address & Contact Info
    currentY += 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("206 / 1, Gangapuram", leftMargin, currentY);
    currentY += 5;
    doc.text("Erode – 638 102", leftMargin, currentY);

    currentY += 6;
    doc.setFont("helvetica", "bold");
    doc.text(`GSTIN: 33AALFG7407L1Z6`, leftMargin, currentY);
    currentY += 5;
    doc.setFont("helvetica", "normal");
    doc.text("Phone: 0424-2534457 | Fax: 0424-2534458", leftMargin, currentY);

    // Document Metadata (Right aligned)
    // We reset Y to top align with Company Name roughly or slightly below
    let metaY = 15;
    doc.setFontSize(9);
    doc.text(`Report Type: ${reportType}`, rightMargin, metaY, { align: 'right' });
    metaY += 5;
    doc.text(`Generated On: ${new Date().toLocaleDateString()}`, rightMargin, metaY, { align: 'right' });
    metaY += 5;
    doc.text(`Generated By: ${generatedBy}`, rightMargin, metaY, { align: 'right' });

    // Horizontal Line
    currentY += 4;
    doc.setLineWidth(0.5);
    doc.line(leftMargin, currentY, rightMargin, currentY);

    // ==============================
    // DOCUMENT TITLE
    // ==============================
    currentY += 10;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(title.toUpperCase(), pageWidth / 2, currentY, { align: 'center' });

    // ==============================
    // SPECIFIC METADATA (Optional)
    // ==============================
    currentY += 10;
    if (metaData) {
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        Object.entries(metaData).forEach(([key, value]) => {
            doc.text(`${key}: ${value}`, leftMargin, currentY);
            currentY += 5;
        });
        currentY += 2; // Extra spacer
    }

    // ==============================
    // BODY CONTENT (TABLE)
    // ==============================
    // Transform simple array of objects to array of arrays for autotable if needed,
    // or just pass the data directly if keys match.
    // Explicitly mapping based on tableColumns ensures order.

    const body = tableData.map(row => tableColumns.map(col => {
        const val = row[col.dataKey];
        return val !== undefined && val !== null ? val : '';
    }));

    const head = [tableColumns.map(col => col.header)];

    autoTable(doc, {
        head: head,
        body: body,
        startY: currentY,
        theme: 'grid', // 'plain' | 'grid' | 'striped'
        headStyles: {
            fillColor: [240, 240, 240], // Light gray header
            textColor: 20, // Nearly black
            fontStyle: 'bold',
            lineWidth: 0.1,
            lineColor: 200
        },
        bodyStyles: {
            textColor: 20,
            lineWidth: 0.1,
            lineColor: 200
        },
        alternateRowStyles: {
            fillColor: [252, 252, 252] // Very light gray for alternate rows
        },
        styles: {
            font: 'helvetica',
            fontSize: 9,
            cellPadding: 3
        },
        didDrawPage: (data) => {
            // Footer
            const str = "This is a system-generated document from Golden Textile Dyers – Inventory & Procurement System.";
            doc.setFontSize(8);
            doc.setTextColor(100);
            const pageSize = doc.internal.pageSize;
            const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
            doc.text(str, pageWidth / 2, pageHeight - 10, { align: 'center' });

            // Page Numbers
            const pageCount = doc.internal.getNumberOfPages();
            doc.text(`Page ${pageCount}`, pageWidth - 15, pageHeight - 10, { align: 'right' });
        }
    });

    // Save
    doc.save(fileName);
};
